version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_4RKAD_CATAPULT_IP}
      APP_PORT: ${APP_4RKAD_CATAPULT_PORT}

  app:
    image: ghcr.io/4rkad/catapult-umbrel:v0.1.0@sha256:e26e790324f961a2a17bee0c4bd7c80d8c9e73e1aaf62b598db012250c16175a
    init: true
    restart: on-failure
    stop_grace_period: 5s
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp
    networks:
      default:
        ipv4_address: ${APP_4RKAD_CATAPULT_IP}
